version: '3.7'
services:
  pokedex_verse:
    image: registry.gitlab.com/arquivei/dockerimages/go:1.23-alpine
    working_dir: /go/src/gitlab.com/arquivei/stark/templates/api
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - './:/go/src/gitlab.com/arquivei/stark/templates/api'
    environment:
      APP_LOG_LEVEL: "DEBUG"
      APP_LOG_HUMAN: "true"
      APP_ADMINSERVER_ADDR: :9000
      APP_SHUTDOWN_TIMEOUT: "1m"
      HTTP_PORT: '8000'
    entrypoint:
      - go
      - run
      - -tags=musl
      - -mod=vendor
      - ./cmd/pokedex_verse
